name: Our CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: run tests
    strategy:
     matrix:
      os: [ubuntu-latest, windows-latest]
      python-version: ["3.8","3.12"]
      #include:
      #exclude: 
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install .[test]
      - name: run test
        run: python -m pytest